[build]
  command = "npm install"
  functions = "netlify/functions"
  publish = "."

[[redirects]]
  from = "/api/news/everything"
  to = "/.netlify/functions/news-everything"
  status = 200

[[redirects]]
  from = "/api/news/top-headlines"
  to = "/.netlify/functions/news-top-headlines"
  status = 200

[[redirects]]
  from = "/api/news/fetch"
  to = "/.netlify/functions/fetch-news"
  status = 200

[[redirects]]
  from = "/api/news/rss"
  to = "/.netlify/functions/fetch-rss"
  status = 200

[[redirects]]
  from = "/api/news/esana"
  to = "/.netlify/functions/fetch-esana"
  status = 200

[[redirects]]
  from = "/api/fb/post"
  to = "/.netlify/functions/fb-post"
  status = 200

[[redirects]]
  from = "/api/fb/video"
  to = "/.netlify/functions/fb-video"
  status = 200

[[redirects]]
  from = "/api/fb/photo"
  to = "/.netlify/functions/fb-photo"
  status = 200

[[redirects]]
  from = "/api/extract-video"
  to = "/.netlify/functions/extract-video"
  status = 200

[[redirects]]
  from = "/api/ai-caption"
  to = "/.netlify/functions/ai-caption"
  status = 200

[[redirects]]
  from = "/api/yt/download"
  to = "/.netlify/functions/yt-download"
  status = 200


[[redirects]]
  from = "/api/proxy-download"
  to = "/.netlify/functions/proxy-download"
  status = 200
